### ISSUE TITLE
How the slope reclassement of I factor works? 

### ISSUE THREAD

**Issue by Kolliv** [Yolecomte/PaPRIKa#6]
1/ Modifier les Reclass_rules slope ? Vérifier si le thru est inclusif ou exclusif , sinon modifier 
0 thru 5 = 4
6 thu 15 = 3 ...

**Comment by Yolecomte** [comment]
According to the doc, it's seems that values are rounded down to the next integer. 
[r.reclass](https://grass.osgeo.org/grass64/manuals/r.reclass.html)

So if the slope value is between 0;4.99999999... it will comes in the 0 thru 4 category (inclusive) but if the slope value is 5.0 it will be change to the 5 thru XX (inclusive) category.

So I think you're right we can change the rules of creation of the reclass_rules file (which are defined in the paprika.py file under the `generate_reclass_rules_slope` function (line 769).

Now, the created file looks like this:
`0 thru 5 = 4
5 thru 15 = 3
15 thru 50 = 2 
50 thru 999999 =1 `
but can easily be change to 
`0 thru 4 = 4
5 thru 14 = 3
15 thru 49 = 2 
50 thru 999999 =1 `
which to my understanding will produce the same result at the end.

If this is the needed behavior, i can fix it.

**Comment by Kolliv** [comment]
Nice !
